### PR TITLE
travis CI checkcase format' coding style

### PR DESCRIPTION
**Pull request by adjivas**
The Travis CI manifest unverify the formatting of any pull request.
This PR add a format's stage to check the application of coding style rule. described by rustfmt.
That imply any unformatted new PR will cause a failure.

### CODE REVIEW

**Comment by adjivas** [comment]
bors try

**Comment by adjivas** [comment]
bors try

**Comment by adjivas** [comment]
bors try

**Comment by adjivas** [comment]
bors try

**Comment by adjivas** [comment]
bors try

**Comment by adjivas** [comment]
@ulysseB Ready for review again.

**Comment by ulysseB** [comment]
Ok. This error is strange: it managed to compile `syntex_syntax` during the tests but not during the documentation generation while no new version of this crate has been published in the meantime. Just to be sure it is not a transient bug, i am going to restart the tests.

bors retry

**Comment by adjivas** [comment]
bors retry

**Pull request merged**
