### PR TITLE
[bandit] Make UCT algorithm customisable

### PR DESCRIPTION
**Pull request by Elarnon**
In order to facilitate performing experiments, this makes the UCT-based
algorithm customizable in term of optimization formula (UCT and pUCT
currently supported), value transformation (execution time vs execution
speed vs log time), sample reduction (max vs mean) and scale.

The UCT and TAG policy are also rewritten to ensure we only read once
node data that can be modified by other threads.

### CODE REVIEW

**Comment by nicoTolly** [comment]
Now that we have two different policies, a concise high-level description of what these policies do would be nice. It could be either comments near both structure definitions, something in the config file (I personnaly don't think they belong there) or something in the README, with appropriate reference to papers and "See algorithm description in README" in code. Otherwise everything seems fine :)

**Comment by Elarnon** [comment]
@nicoTolly I added some descriptions for the available algorithms, does this look OK to you?  I don't really want to go into *too much* details/explanations as I think this is not the place for it, but there are references and search terms if people want to understand this better.

**Comment by Elarnon** [comment]
bors retry

**Pull request merged**
