### PR TITLE
Fix the cuda backend, benches and tests.

### PR DESCRIPTION
**Pull request by ulysseB**
The cuda backend did not correctly link and telamon-kernel cuda benches and tests did not work. I also removed some `unwrap!` and `extern crate` statements from telamon-kernels.

### CODE REVIEW

**Comment by Elarnon** [comment]
@ulysseB any idea what went wrong on travis? I can confirm this patch works on ficus at least.

**Comment by ulysseB** [comment]
Sorry. Didn't had time to come back to this PR. Their is two problems. One is just that I forgot to run rustfmt. The other is that `cargo check --all` use default features, and that the cuda backend requires the cuda headers by default.

I will try to have travis install it. Otherwise, I will just remove the default feature.

**Comment by ulysseB** [comment]
bors try

**Comment by ulysseB** [comment]
bors try

**Comment by ulysseB** [comment]
bors try

**Comment by ulysseB** [comment]
bors try

**Comment by ulysseB** [comment]
bors try

**Comment by ulysseB** [comment]
bors try

**Comment by ulysseB** [comment]
bors try

**Comment by ulysseB** [comment]
bors try

**Comment by ulysseB** [comment]
bors try

**Comment by ulysseB** [comment]
bors try

**Comment by ulysseB** [comment]
bors try

**Comment by ulysseB** [comment]
bors try

**Comment by ulysseB** [comment]
bors try

**Comment by ulysseB** [comment]
bors try

**Comment by ulysseB** [comment]
bors try

**Comment by ulysseB** [comment]
bors try

**Comment by ulysseB** [comment]
bors try

**Comment by ulysseB** [comment]
bors try

**Comment by ulysseB** [comment]
bors try

**Comment by ulysseB** [comment]
bors r=elarnon

**Comment by Elarnon** [comment]
\o/

**Pull request merged**
